<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' == '' ">2.0.0.0</Version>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' != '' ">$(BUILD_BUILDNUMBER)</Version>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Li Haobin</Authors>
    <Description>A framework for Object-Oriented Discrete Event Simulation</Description>
    <Company>ISEM Department, National University of Singapore</Company>
    <Copyright>Copyright © 2015-2026 O²DES.NET</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>http://www.o2des.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/li-haobin/O2DES.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>O2DES.Net Discrete-Event Simulation</PackageTags>
	<PackageVersion>3.8.3</PackageVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
	<None Include="icon.png" Pack="true" PackagePath="\" />
	<None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
